### ISSUE TITLE
USER STORY: List of available courses

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#11]
As a **visitor**, I can **click on a link in the navigation menu** to **see a list of available courses**.
### Acceptance Criteria
- [x] There is a list of all courses available at a URL.
- [x] Theres is a navigation menu containing a link to the URL to the course list.

### Tasks
- [x] Create course list view
- [x] Create base template with navigation menu containing a link to the course list page
- [x] Create course list template
- [x] Register URL
- [x] Test view
