### ISSUE TITLE
USER STORY: Course registration for visitors

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#12]
As a **visitor**, I can **fill out a registration form** to **sign up for a course**.

### Acceptance Criteria
- [x] A visitor can sign up for courses without having to create a user account.
- [x] The registration will be saved in the database upon submitting a registration form.

### Tasks
- [x] Create model for visitor registrations
- [x] Create registration form and view
- [x] Add template
