### ISSUE TITLE
USER STORY: Calculate fees during sign-up

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#13]
As a **visitor** or a **logged-in user**, I can **see the fees for the course, depending on how many sessions I have selected**.

### Acceptance Criteria
- [x] Upon filling out a course registration form the user can see, what the course fees will be.
- [x] The course fees change, depending on if the user selects single sessions or the entire course.
- [x] The course fee will be stored with the registration upon submitting the form.

### Tasks
- [x] Add course sessions to course registration form
- [x] Create logic for calculating the course fees to the post method of the course registration view.
- [x] Add javascript to the template in order to display the fees dynamically.
- [x] Write tests for view
