### ISSUE TITLE
USER STORY: Course registration confirmation email

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#14]
As a **visitor** or a **logged-in user**, I can **receive an email as confirmation**, **after signing up for a course, containing course and payment details so that I have a backup of all relevant details**.

### Acceptance Criteria
- [x] After signing up for a course users will receive an email confirming the successful registration.
- [x] The email contains details about the course and the registration.

### Tasks
- [x] Update RegisterCourse view to send email upon successful registration
- [x] Include course and registration details in email
