### ISSUE TITLE
USER STORY: Edit course registrations

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#16]
As a **logged-in user**, I can **edit my current registrations** so that **I can update information**.

### Acceptance Criteria
- [x] Users can see a list of their current registrations.
- [x] Users can click on a current registration and be redirected to a form for editing their registration.
- [x] After submitting the form the updated data will be stored in the database.

### Tasks
- [x] Create view to list registrations.
- [x] Create template for registration list with edit registration button.
- [x] Create view for editing registration
- [x] Test views
