### ISSUE TITLE
USER STORY: Create User Account

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#2]
As a **visitor**, I can **create a user account** so that I can **log in and store my information**.

### Acceptance Criteria:

- [x] There is a Sign Up button accessible from everywhere on the website
- [x] Upon clicking on the Sign Up button a user registration form is displayed
- [x] Upon successful registration a new user is created in the database.

### Tasks:

- [x] Install and setup Django-allauth
- [x] Create UserProfile model with additional fields
- [x] Add Sign Up button to base template and link to allauth registration form
- [x] Create user profile view
- [x] Create user profile template
- [x] Create user profile form
