### ISSUE TITLE
USER STORY: Cancel exam application

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#21]
As a **logged-in user**, I can **cancel exam applications for current registrations**.

### Acceptance Criteria
- [ ] In the users registrations list, there is a button for cancelling an exam application.
- [ ] Upon clicking the button, the user is asked to confirm the cancellation.
- [ ] After confirming the registration is updated with the new setting.

### Tasks
- [ ] Update course registration template to display a button for cancelling an exam application
- [ ] Create confirmation template
- [ ] Create view
- [ ] Write tests for view
