### ISSUE TITLE
USER STORY: Update rank notification

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#22]
As a **logged-in user**, I can **receive a notification after logging in if I have previously applied for an exam** so that **I can update my user profile accordingly**.

### Acceptance Criteria
- [x] After applying for an exam and after the course has passed, the user will be presented with a dialogue asking if they want to update their grade.
- [x] If the user confirms that they passed their exam the registration will be updated to include the information in the exam_passed field.

### Tasks
- [x] Add logic for checking if the user has applied for an exam and if the course has passed to user profile view
- [x] Create view for displaying the notification.
- [x] Add exam_passed field to CourseRegistration model
- [x] Display if exam has been passed in  the course registration view
- [x] Write tests for views
