### ISSUE TITLE
USER STORY: Website Navigation

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#23]
As a **visitor** or **logged-in user**, I can **easily navigate through different sections of the website using a clear and intuitive navigation menu displayed on all pages**. (MVP)

### Acceptance Criteria
- [x] There is a navigation menu displayed on all pages.
- [x] The navigation menu is responsive so that it is easily accessible on all devices

### Tasks
- [x] Add bootstrap classes and js to navigation in order to style it and make it responsive
