### ISSUE TITLE
USER STORY: Current courses and registrations on start page

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#26]
As a **user**, I want **the start page to display the latest courses and currently open course registrations** so that **I can quickly access them**.

### Acceptance Criteria
- [x] There is a list of upcoming courses on the home page.
- [x] Users can see which courses are open for registration.

### Tasks
- [x] Add list of upcoming courses to index.html
- [x] Mark courses with open registrations with a badge
