### ISSUE TITLE
USER STORY: Access information about organization

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#27]
As a **visitor or logged-in user**, I can **access information about Aikido, about the organization** so that **I can learn about the organization and know where I can train Aikido**.

### Acceptance Criteria
- [x] There are pages for accessing information about the organization accessible from the navigation menu
- [x] There is a page with links to the websites of all Aikido Dojos which are part of the organization

### Tasks
- [x] Create pages for information about Aikido, about Danbw, about the Dojos
- [x] Include pages in navigation menu
