### ISSUE TITLE
USER STORY: Contact form

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#28]
As a **visitor or logged-in user**, I can **fill out a contact form** so that **I can get in touch with the team**.

### Acceptance Criteria
- [x] There is a contact page, which is accessible from the footer.
- [x] There is a contact form on the contact page, which allows users to contact the organization.

### Tasks
- [x] Set up email backend
- [x] Create contact view
- [x] Create contact form
- [x] Create template
