### ISSUE TITLE
USER STORY: Contact options

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#29]
As a **visitor or logged-in user**, I can **see ways of getting in touch with the team, such as an e-mail address**, in order **to provide me with multiple contact options**. (MVP)

### Acceptance Criteria
- [x] There is a contact page on the website
- [x] The page contains an email address

### Tasks
- [x] Create Contact view
- [x] Create template for contact view
- [x] Register url
