### ISSUE TITLE
USER STORY: Login feature

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#3]
As a **user**, I can **log in to my account** by **clicking on a login button from anywhere on the Website**.

### Acceptance Criteria
- [x] There is a login button, which is accessible from everywhere on the website.
- [x] Upon clicking on the button the user is presented with a form for loggingn in with their user credentials.

### Tasks
- [x] Add login button to base template
- [x] Create login form
