### ISSUE TITLE
USER STORY: Duplicate existing Course

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#31]
As a **staff member**, I can **duplicate existing courses**.

### Acceptance Criteria
- [x] Staff members can see existing courses in the Django backend and duplicate a course by clicking on a course in the list and select a duplicate course method.

### Tasks
- [x] Create method for course duplication and register it in the admin view
- [x] Write tests for duplication method
