### ISSUE TITLE
USER STORY: Update or delete courses

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#32]
As a **staff member**, I can **update or delete existing courses**.

### Acceptance Criteria
- [x] Staff members can update courses from the Django admin backend
- [x] Staff members can delete courses from the Django admin backend
- [x] Staff members can see the properties of existing courses in the django admin backend course list.

### Tasks
- [x] Adjust admin view for courses to include course details.
