### ISSUE TITLE
USER STORY: Course registrations overview

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#33]
As a **staff member**, I can **click on a course to see all registrations for a course**. (MVP)

### Acceptance Criteria
- [x] When clicking on a Course in the Django backend, staff users can see a list of all registrations for the course.

### Tasks
- [x] Create CourseRegistration model
- [x] Create CourseSessions model
- [x] Register CourseRegistrations as a field of Courses in the admin view as an inline
- [x] Write tests for CourseRegistration and CourseSessions model
