### ISSUE TITLE
USER STORY: Create and edit pages

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#35]
As a **staff member**, I can **create new pages and edit existing pages** so that **I can add new content to the website**.

### Acceptance Criteria
- [x] Staff members can add pages from the admin view
- [x] Staff members can define for pages
- [x] Published pages are displayed in the main navigation automatically
- [x] Staff members can use a WYSIWIG editor to edit the page contents

### Tasks
- [x] Create page model
- [x] Create category model
- [x] Register models to the admin site
- [x] Create views for page display
- [x] Update base.html template to include links to pages sorted by category in the navigation
- [x] Write tests for models and views
