### ISSUE TITLE
USER STORY: UI design

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#36]
As a **visitor** or a **logged-in user**, I want **the website to have a responsive, consistent and visually appealing UI design** in order to **elicit a positive response during my visit**.

### Acceptance Criteria
- [x] The website has a consistent layout and styling over all pages.
- [x] The website is responsive for different screen sizes.
- [x]  The website uses colors and images which represent the organisation.

### Tasks
- [x] Add bootstrap to base template
- [x] Create basic bootstrap layout and styling
- [x] Include images on the home page
