### ISSUE TITLE
USER STORY: Logout feature

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#4]
As a **user**, I can **log out from my account** by **clicking on a Logout button from anywhere on the website**.

### Acceptance Criteria
- [x] There is a logout button accessible from anywhere on the website
- [x] Upon clicking on the logout button the user is logged out from the system.

### Tasks
- [x] Add logout button to base template
- [x] Show logout button only for authenticated users
