### ISSUE TITLE
USER STORY: Get Registration count in course list

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#42]
As a **staff member** I can **see the number of registrations for each course in the course list in the Django admin backend** so that **I can access that information without having to click on a course first.**

### Acceptance Criteria
- [x] The number of registrations for each course are displayed in the course list in the Django admin view.

### Tasks
- [x] Create method for getting registration count
- [x] Add method to courses_list display
- [x] Write tests for method
