### ISSUE TITLE
USER STORY: Course Registration for logged-in users

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#43]
As a **logged-in user**, I can **fill out a sign-up form** to **sign up for a course**.

### Acceptance Criteria
- [x] A logged-in user can click on a link in the course with open registration status and will be directed to to a registration form.
- [x] The registration-form provides fields for all necessary details.
- [x] Upon filling out the form, a new registration will be stored in the database.

### Tasks
- [x] Create course registration form
- [x] Create registration form template
- [x] Create view
- [x] Register url
- [x] Write tests for form and view
