### ISSUE TITLE
USER STORY: Use WYSIWYG editor for text fields in Django backend

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#44]
As a **staff member* I can **use a WYSIWIG editor in the Django backend** so that **I have more control over layout and styling.**

### Acceptance Criteria
- [x] There is a WYSIWIG editor installed that staff members can use for editing text fields.

### Tasks
- [x] Install and setup summernote.
- [x] Adjust admin view to use summernote fields for text fields.
