### ISSUE TITLE
USER STORY: Account confirmation

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#5]
As a **user**, I can **receive an email** as **confirmation when I create a user account**. 

### Acceptance Criteria
- [x] After creating an account the user will receive an e-mail as confirmation.
- [x] The email contains relevant details about the account and a confirmation message.  

### Tasks
- [x] Set up email functionality in Django
- [x] Send confirmation e-mail after account creation
- [x] Create sendmail function in view to send the confirmation email upon successful account creation
