### ISSUE TITLE
USER STORY: Custom 404 error page

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#50]
As a **Visitor or logged-in user** I can **see a custom error page with a link to the homepage**, when I try to access a URL that doesn't exist.

### Acceptance Criteria
- [x] There is a custom error page with a link to the homepage.
- [x] The page is displayed when a 404 error comes up instead of the default 404 error page.

### Tasks
- [x] Create a custom 404 error template
