### ISSUE TITLE
USER STORY: Comply with Accessibility Guidelines

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#55]
As a **user**, I want **the website to comply with accessibility guidelines** so that **I can access it with screen readers or other assistive technologies**.

### Acceptance Criteria
- [x] The templates use accessibility labels and elements where appropriate.

### Tasks
- [x] Use aria-labels where necessary
- [x] Fix suggestions from 
- [x] User semantic html elements in base template
