### ISSUE TITLE
USER STORY: Messages

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#56]
As a **visitor or logged-in user** I can **see messages with different colors** so that **I can get feedback for my actions.**

### Acceptance Criteria
- [ ] There are messages displayed, when the user submits forms.
- [ ] The messages have different colors depending on their type. 

### Tasks
- [ ] Add bootstrap alert class to messages
- [ ] Set up messages typse in settings.py
- [ ] Add styling to alerts types
