### ISSUE TITLE
USER STORY: View user profile

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#6]
As a **logged-in user**, I can **view my user profile**.

### Acceptance Criteria
- [x] There is a link in the navigation for logged in user which brings them to their user profile.
- [x] The user profile displays user data and includes a link to the user's course registration list. 

### Tasks
- [x] Create UserProfile model to extend User model
- [x] Create view for user profiles
- [x] Update template for user profile
- [x] Update base template
- [x] Test model and view
