### ISSUE TITLE
USER STORY: Update User Profile

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#7]
As a **logged-in user**, I can **update my user profile**.

### Acceptance Criteria
- [x] A user can click on a link to edit the user's profile on the profile page.
- [x] Upon clicking that link, a form for editing the user's data will appear.
- [x] After submitting the form the updated data is stored in the database.

### Tasks
- [x] Create form for editing user profile with the following fields: first name, last name, username, email, grade
- [x] Create view for editing the profile
- [x] Register urls
- [x] Write tests
