### ISSUE TITLE
USER STORY: Reset Password

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#8]
As a **logged-in user**, I can **reset my password**. 

### Acceptance Criteria
- [x] Users can reset their password by clicking on a link on their profile page

### Tasks
- [x] Include link to account_change_password url from allauth in user profile template
- [x] Adjust allauth change password template
