### ISSUE TITLE
USER STORY: Delete Account

### ISSUE THREAD

**Issue by nacht-falter** [nacht-falter/aikido-course-website-django#9]
As a **logged-in user**, I can **delete my account**.

### Acceptance Criteria
- [x] Users can delete their account by clicking on a link
- [x] After the user confirms they want to delete the account, the user will be removed from the system

### Tasks
- [x] Create delete user view
- [x] Create delete user template
- [x] Write tests for view
